"""Interactive config initialization.

`bssync init` walks the user through creating a `bookstack.yaml` config:
prompts for the BookStack URL, API token ID and secret, tests the
connection, and writes a starter config file.
"""

import getpass
import sys
from pathlib import Path

from bssync.client import BookStackClient

CONFIG_TEMPLATE = """# bssync config — generated by `bssync init`
# This file contains API credentials — do not commit to version control.
# bssync's .gitignore already excludes it.

bookstack:
  url: {url}
  token_id: "{token_id}"
  token_secret: "{token_secret}"

# ─── Publishing map ───
# Add entries here to track local markdown files. Each entry maps a local
# file to a BookStack page. See README for full field reference.
#
# Quick workflow:
#   1. bssync ls --missing                    # see what's on BookStack
#   2. bssync pull --new --book <book-name>   # print YAML snippets to paste
#   3. Paste snippets into the `publish:` list below
#   4. bssync pull                            # fetch content to local files

publish: []
"""


def cmd_init(config_path: Path, non_interactive: bool = False):
    """Interactive config setup. Writes a new bookstack.yaml at the
    given path. Refuses to overwrite an existing file (user must delete
    or choose a different path first)."""
    if config_path.exists():
        print(f"Error: {config_path} already exists.")
        print("Delete it first, or use -c to pick a different path.")
        sys.exit(1)

    if non_interactive:
        print("Error: bssync init requires an interactive terminal.")
        sys.exit(1)

    print("\nbssync init — configure a new BookStack connection")
    print("─" * 50)
    print()

    url = _prompt("BookStack URL (e.g. https://docs.example.com)",
                  required=True)
    url = url.rstrip("/")

    print()
    print("API token — create one at:")
    print(f"  {url}/settings/users/ (select your user → Create Token)")
    print()

    token_id = _prompt("Token ID", required=True)
    token_secret = _prompt_secret("Token secret")

    # Test the connection before writing
    print()
    print("Testing connection...")
    client = BookStackClient(url=url, token_id=token_id,
                             token_secret=token_secret)
    if not client.verify_connection():
        print("\nConnection failed. Check the URL and credentials and try again.")
        print("No config file was written.")
        sys.exit(1)

    print("Connected.")

    # Write the config
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(CONFIG_TEMPLATE.format(
        url=url, token_id=token_id, token_secret=token_secret))

    print(f"\nConfig written to {config_path}")
    print("\nNext steps:")
    print(f"  bssync -c {config_path} ls                    # see what's on BookStack")
    print(f"  bssync -c {config_path} pull --new --book X   # find untracked pages")
    print(f"  # edit {config_path} to add entries, then:")
    print(f"  bssync -c {config_path} pull                  # fetch content locally")
    print()


def _prompt(label: str, default: str = "", required: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        try:
            value = input(f"{label}{suffix}: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nAborted.")
            sys.exit(1)
        if not value and default:
            return default
        if value:
            return value
        if not required:
            return ""
        print("This field is required.")


def _prompt_secret(label: str) -> str:
    while True:
        try:
            value = getpass.getpass(f"{label} (hidden): ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nAborted.")
            sys.exit(1)
        if value:
            return value
        print("This field is required.")
